# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

- id: primary-example_vip
  type: group
  role: [primary-example_vip]
  requires: [deploy_start]
  required_for: [deploy_end]
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig,
      hosts, firewall, ssl-keys-saving, ssl-add-trust-chain, hosts, cluster,
      virtual_ips]
  parameters:
    strategy:
      type: one_by_one

- id: example_vip
  type: group
  role: [example_vip]
  requires: [deploy_start, primary-example_vip]
  required_for: [deploy_end]
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig,
      hosts, firewall, ssl-keys-saving, ssl-add-trust-chain, hosts, cluster,
      virtual_ips]
  parameters:
    strategy:
      type: parallel

- id: deploy-example-vip-override-task
  type: puppet
  groups: [primary-example_vip, example_vip]
  required_for: [cluster]
  requires: [globals]
  parameters:
    puppet_manifest: deploy-example-vip-override.pp
    puppet_modules: /etc/puppet/modules
    timeout: 600
